development:
  adapter: postgresql
  host: localhost
  database: development
  encoding: UTF8

test:
  adapter: postgresql
  host: localhost
  database: test
  encoding: UTF8

production:
  adapter: postgresql
  host: localhost
  database: test
  encoding: UTF8